version: "3.7"
services:
  db:
    image: postgres:12.7
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=p@ssw0rd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ie2
    ports:
      - "5432"
  rmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    expose: 
      - "5672"
  api:
    image: ie2api:latest
    depends_on:
      - "rmq"
      - "db"
    build:
      no_cache: true
      context: .
      dockerfile: Dockerfile
      tags:
        - "ie2api:latest"
    environment:
      - RMQ_URL=rmq:5672
      - RMQ_UNAME=guest
      - RMQ_PWD=guest
      - RMQ_QNAME=TestQueue
      - DB_USER=postgres
      - DB_PWD=p@ssw0rd
      - DB_NAME=ie2
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8080:8080"